config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'sobre', to: 'pages#sobre'
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :arranjos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arranjo.rb
class Arranjo < ApplicationRecord
   mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, only: [:edit, :new]
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: [:index, :show], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [:index,], unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/arranjos_controller.rb
class ArranjosController < ApplicationController
  before_action :set_arranjo, only:[:edit, :update, :show, :destroy]
  def index
    @arranjos = policy_scope(Arranjo).order('created_at DESC')
  end

  def new
    @arranjo = Arranjo.new
  end

  def create
    @arranjo = Arranjo.new(set_params)
    if @arranjo.save
      redirect_to arranjo_path(@arranjo)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @arranjo.update(set_params)
    if @arranjo.save
      redirect_to arranjo_path(@arranjo)
    else
      render :new
    end
  end

  def show
  end

  def destroy
    @arranjo.destroy
    redirect_to arranjos_path
  end

  private

  def set_params
    params.require(:arranjo).permit(:name, :description, :deparment, :dimentions, :hastes, :composition, :avalable_membership, :old_url_photo, :photo, :photo_cahe)
  end

  def set_arranjo
    @arranjo = Arranjo.find(params[:id])
    authorize @arranjo
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def sobre
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/arranjos/edit.html.erb
<div class="container">
  <h1>Editar Arranjo</h1>
  <%= render 'shared/form_arranjo', arranjo: @arranjo %>
</div>

app/views/arranjos/index.html.erb
<div class="container">
  <h1>Conheça nossos arranjos</h1>
  <div class="row">
    <% @arranjos.each do |arranjo| %>
      <%= render 'shared/card_arranjo', arranjo: arranjo %>
    <% end %>
  </div>

</div>

app/views/arranjos/new.html.erb
<div class="container">
  <h1>Criar novo Arranjo</h1>
  <%= render 'shared/form_arranjo', arranjo: @arranjo %>
</div>

app/views/arranjos/show.html.erb
<div class="container">
  <div class="main-content">
    <h1><%= @arranjo.name  %></h1>
    <% if user_signed_in? && current_user.site_owner %>
      <%= render 'shared/owner_actions', arranjo: @arranjo  %>
    <% end  %>
    <p><%= @arranjo.description %></p>
    <%= cl_image_tag @arranjo.photo, height: 500, width: 400, crop: :fill%>
    <p>Disponível por assinatura no plano: <%= @arranjo.available_membership  %></p>
    <button class='btn btn-primary bnt-lg'>Assinar já</button>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Flores Alessandra</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <div class="outside-wrapper">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
      <%= javascript_include_tag 'application' %>
      <%= javascript_pack_tag 'application' %>

    </div>
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/main_banner'  %>

app/views/pages/sobre.html.erb
<div class="container">
  <div class="row">
    <div class="justify-center">
      <div class="col-xs-12 col-sm-offset-2 col-sm-4">
        <img src="http://res.cloudinary.com/drfvlo6ah/image/upload/v1526421142/photo_ale.jpg" alt="">
        <p class='image-footer'> Alessandra Lima</p>
      </div>
      <div class="col-xs-12 col-sm-4">
        <p class='fine-font'>
        "Não há nada mais encantador do que trabalhar com o que é perfeito por natureza.
        Reger uma orquestra de beleza e perfeição me desafia, me move, me faz vibrar."
        Alessandra Lima"</p>

        <p class='solid-font'>Parte da nova geração em design floral, Alessandra acredita nas flores como a mais delicada forma de expressão. Por isso optou por suas cores, perfumes e harmonia como ofício. Elabora arranjos com respeito e envolvimento com a vida: equilibra a beleza como uma reverência à Natureza.  </p>

        <p class='solid-font'>Sua filosofia sustentável vai desde a escolha de seus parceiros até a composição de arranjos em água, dispensando a espuma floral. Sua técnica permite a criação em uma base fluida que leva à melhor nutrição
        das flores e folhagens - um desafio que se tornou uma
        paixão na vida da florista.</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_card_arranjo.html.erb
<div class="col-xs-12 col-sm-4">
  <div class="card-arranjo" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path arranjo.photo, height: 300, width: 400, crop: :fill %>');">
    <div class="card-category"><%= arranjo.department %></div>
    <div class="card-description">
      <h2><%= arranjo.name  %></h2>
      <p><% "#{arranjo.description.truncate(15)}" %></p>
    </div>
    <a class="card-link" href="<%= arranjo_path(arranjo)  %>" ></a>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Feito com <i class="fa fa-heart"></i>
  </div>
</div>

app/views/shared/_form_arranjo.html.erb
<%= simple_form_for(arranjo) do |f| %>
  <%= f.input :name, label: 'Nome do arranjo', placeholder: 'Seja criativo' %>
  <%= f.input :description, label: 'Descrição do arranjo', placeholder: 'O que faz deste um arranjo especial?' %>
  <%= f.input :composition, label: 'Composição', placeholder: 'Que tipo de flores tem aquí?' %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit class: 'btn btn-primary btn-lg'%>
<% end %>

app/views/shared/_main_banner.html.erb
<div class="main-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('http://res.cloudinary.com/drfvlo6ah/image/upload/v1526414052/9131156_orig.jpg');">
  <div class="banner-content">
    <h1>O florista vai até você</h1>
    <p>Seu espaço com flores fica muito melhor </p>
    <%= link_to 'Começar Agora', arranjos_path, class: 'btn btn-primary btn-lg' %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Flores", arranjos_path, class: "navbar-wagon-item navbar-wagon-link" %>


      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "https://cdn.vectorstock.com/i/1000x1000/34/52/user-icon-male-person-symbol-profile-avatar-sign-vector-19413452.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "Flores", arranjos_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Sobre Nós", sobre_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

        <li><a href="<%= new_user_session_path %>">Login</a></li>
        <li><a href="<%= arranjos_path %>">Flores</a></li>
        <li><a href="<%= sobre_path %>">Sobre Nós</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_owner_actions.html.erb
<div class="btn-group">
  <%= link_to 'Editar', edit_arranjo_path(arranjo), class: 'btn btn-success btn-md'  %>
  <%= link_to 'Excluir', arranjo_path(arranjo), method: :delete, data: {confirm: "esta acão não pode ser desfeita"}, class: 'btn btn-danger btn-md'  %>
</div>